### PR TITLE
Sbs titlepage tests

### PR DESCRIPTION
**Pull request by egli**
All the tests pass now and css and boiler-plate generation should be the way we want it

### CODE REVIEW

**Comment by bertfrees** [comment]
Can't run the test suite either.

**Comment by bertfrees** [comment]
Just like with https://github.com/sbsdev/pipeline-mod-sbs/issues/9 I suggest we wait with merging this until we've solved the performance problem.

**Comment by egli** [comment]
Hm, I guess it is the more sensible thing to do. @mixa72 wanted to do some manual testing though. I guess he will have to wait or I can install a snapshot off the branch.

**Comment by bertfrees** [comment]
Yes you could deploy off the branch, as long as Mischa knows that the next deployment will overwrite it again.

**Comment by bertfrees** [comment]
Rebased this branch as "sbs-49".

**Comment by mixa72** [comment]
ok

**Pull request closed without merging**
